[package]
name = "memcached"
version = "0.1.0"
authors = ["Jakub Wieczorek <jakub.adam.wieczorek@gmail.com>"]
edition = "2018"

[[bin]]
name = "memcached"
path = "main.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
